#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu2402
    username: usuarioubuntu
    password: $6$saltsalt$M8TwNCHWfwujBnGKtY3y4H42n3ak8fpM6LUKLGmesj3LDKVNaYIH9HetLApg3k9gUVpi99HX.wEjt3hACVy1/0  
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - build-essential
    - htop
    - git                       # adicione o nome do pacote aqui
    - python3                   # outro pacote para adicionar
    - python3-pip               # mais um pacote
  locale: pt_BR
  keyboard:
    layout: br
    variant: ''
  network:
    network:
      version: 2
      ethernets:
        enp0s3:
          dhcp4: true
