#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: nomad-000
    username: nomad
    password: $y$j9T$fE6zLV7uFhbwKXP4fWTSe/$BBMaCcnBVZnuJVW3BwnNsFFuc0iMzWqiNpwYsyxvpp0 
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - build-essential
    - git
    - python3
    - python3-pip
    - wget
    - curl
    - code --classic
  locale: pt_BR
  keyboard:
    layout: br
    variant: ''
  network:
    network:
      version: 2
      ethernets:
        enp0s3:
          dhcp4: true
      
  snaps:
    - name: slack
      classic: true
      
  late-commands:
    - wget -O /target/postinstall.sh https://raw.githubusercontent.com/FernandinhoLeste/Ubuntu2402/main/postinstall.sh
    - curtin in-target -- bash /postinstall.sh
    - rm /target/postinstall.sh
    
    
