#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: nomad-000
    username: 
    password: $6$saltsalt$M8TwNCHWfwujBnGKtY3y4H42n3ak8fpM6LUKLGmesj3LDKVNaYIH9HetLApg3k9gUVpi99HX.wEjt3hACVy1/0  
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - build-essential
    - git                       
    - python3                   
    - python3-pip
  locale: pt_BR
  keyboard:
    layout: br
    variant: ''
  network:
    network:
      version: 2
      ethernets:
        enp0s3:
          dhcp4: true
      wifis:
        wlp0s20f3:          # Substitua pelo nome da sua interface wifi
          dhcp4: true
          dhcp6: false
          access-points:
            "Nmd_Guest":   # Substitua pelo nome da sua rede
              password: "nomad2023@@@@" # Substitua pela senha da sua rede
  snaps:
    - name: slack
      classic: true
