#cloud-config
instalação automática:
    versão: 1

localidade: pt_BR
teclado:
    layout: br
    variante: ""

armazenar:
    disposição:
        nome: lvm
        tamanho: auto  # Define o tamanho da partição como "auto" para usar todo o espaço disponível

identidade:
    nome do host: Nomad
    nome de usuário: Nomad
    senha: 1865a77e7cae167328b6728831677d0a3c013a5bc38f4cb490033199a1c32644d09b63e7e99928e6085e8e68c7ac649d55e082de5e5386c851df270d5e8472a6

instantâneos:
    - nome: vá
      canal: 1,20/estável
      clássico: verdadeiro

seleções debconf: |
    bind9 bind9/run-resolvconf booleano falso

pacotes:
    - libreoffice
    - bind9  # Corrigido para instalar o servidor DNS Bind9

dados do usuário:
    desativar_root: falso

comandos tardios:
    - sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=30/' /target/etc/default/grub  # Corrigido para sed -i
